language: c
services:
    - docker

matrix:
    include:
        - env: ITEST_TARGET=itest_xenial
        - env: ITEST_TARGET=itest_bionic
        - arch: arm64
          env: ITEST_TARGET=itest_xenial
        - arch: arm64
          env: ITEST_TARGET=itest_bionic
        - env: ITEST_TARGET=itest_buster
        - env: ITEST_TARGET=itest_tox
        - arch: arm64
          env: ITEST_TARGET=itest_tox
        - arch: arm64
          env: ITEST_TARGET=itest_buster


script:
   - make "$ITEST_TARGET"

after_script:
   - ci/artifact-upload
